#!/usr/bin/env python3.10
"""PV11 alpha=0 manipulation gate. FROZEN BEFORE ANY MODEL DATA EXISTS.

Pre-registering two rules is not the same as fixing their implementation, so
every free parameter is settled here, in this file, while no PV11 model output
exists to tune them against. Once data exists, DO NOT EDIT THIS FILE.

WHAT THE GATE ASKS
------------------
Not "is the model good at the task". It asks whether this controlled interface
elicits the two PREREQUISITE sensitivities without which a steered contrast has
nothing to move:

  M1  Does first-step COMMIT respond to EVIDENCE STRENGTH?
      P(COMMIT | strong) - P(COMMIT | weak) >= 0.15

  M2  Does first-step probe sampling respond to SAMPLE SIZE, holding the
      displayed rate fixed?
      P(sample probe | low_n/low_rate) - P(sample probe | matched_n/low_rate)
      >= 0.15

WHY M2 USES ONLY THE LOW-RATE CELLS
-----------------------------------
In the high_rate cells the probe is the displayed leader, so sampling it cannot
be separated from chasing its rate. That conflation is exactly what invalidated
PV10-C's `next_sample_targets_competitor` = .774 (291 of its 308 "aligned"
rounds sampled the MOST-sampled arm). The low-rate contrast holds the probe's
label, display row, displayed rate and the other three arms identical and
varies ONLY its sample size.

WHY NEITHER RULE HAS AN ABSOLUTE FLOOR
--------------------------------------
An absolute floor such as "probe sampled in >= 4/20 states" sits at the K=4
random-sampling rate (~.25), so uniform random behaviour would PASS it. Under
random sampling the cross-cell DIFFERENCE is ~0, so only differences are gated.
A per-cell rate is descriptive and is printed, never gated.

FROZEN FREE PARAMETERS
----------------------
  * denominator: ITT. All 20 states of a cell. invalid counts in the
    denominator and in no numerator. valid-only is printed ALONGSIDE with its
    own explicit denominator, and is never the gate.
  * "first step" means `first_action`, the record's own field. It is the only
    strictly state-matched quantity; nothing downstream is read here.
  * M1 pools the two horizons. The per-horizon split is printed and read by a
    human; it is deliberately NOT mechanized, because a threshold invented for
    it would be the post-hoc freedom this file exists to prevent.
  * comparisons are `>=` against 0.15, as pre-registered: a tie at exactly
    0.15 PASSES and is not re-adjudicated. Applied with a 1e-9 tolerance so a
    float ULP cannot decide the verdict -- with n=20 the attainable differences
    are multiples of 0.025, so this cannot move a real result. See TOL.
  * missing / duplicate / extra states are a hard ERROR, never a silent subset.
  * interface validity (>= 0.90 parseable first actions) is reported as a
    separate INTERFACE check. It is not a capability criterion and does not
    enter M1/M2.

ON FAILURE
----------
Manipulation-gate failure does not trigger prompt iteration. It means that this
controlled interface did not elicit the prerequisite behavior needed for an
interpretable steering test; no steered cells are run.

Usage:
    python3.10 analyze_bandit_pv11_gate.py --result <dir_or_json>
    python3.10 analyze_bandit_pv11_gate.py --selftest
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

M1_THRESHOLD = 0.15
M2_THRESHOLD = 0.15
INTERFACE_THRESHOLD = 0.90
N_PER_CELL = 20

# Comparisons are made with a 1e-9 absolute tolerance. This is NOT threshold
# softening: with n=20 per cell every attainable difference is a multiple of
# 1/40 = 0.025, so the nearest real values to 0.15 are 0.125 and 0.175 and no
# tolerance below ~0.01 can move a verdict. What it prevents is a float ULP
# deciding PASS/FAIL: 9/20 - 6/20 evaluates to 0.15000000000000002 while
# 7/20 - 4/20 evaluates to 0.14999999999999997, so a bare `>=` would give two
# differences that are BOTH exactly 3/20 opposite verdicts depending on which
# cells produced them. Caught by --selftest before any data existed.
TOL = 1e-9


def _at_least(value: float, threshold: float) -> bool:
    """`value >= threshold`, immune to representation error. See TOL."""
    return value >= threshold - TOL

COMMITMENT_CELLS = ("weak/short", "weak/long", "strong/short", "strong/long")
ACQUISITION_CELLS = ("low_n/low_rate", "low_n/high_rate",
                     "matched_n/low_rate", "matched_n/high_rate")


# ─────────────────────────────── loading ────────────────────────────────────

def load_runs(path: Path) -> tuple[list[dict], dict]:
    """Read the driver's output. Fails closed on a schema mismatch.

    The driver writes `{"runs": [...]}`. PV10's gate loader read `"episodes"`
    and silently wrapped the whole payload as ONE pseudo-episode when that key
    was absent, reporting a spurious FAIL at n=1 without erroring. Freezing the
    evaluator's HASH did not catch it, because the manifest verifies the
    evaluator, not that the evaluator and the driver were ever wired together.
    Hence: unknown schema -> hard error, and `test_pv11_gate_end_to_end.py`
    drives this function with the DRIVER's real output.
    """
    if path.is_dir():
        candidates = sorted(path.glob("*.json"))
        if not candidates:
            raise SystemExit(f"no JSON in {path}")
        if len(candidates) > 1:
            raise SystemExit(
                f"{path} holds {len(candidates)} JSON files; name one "
                f"explicitly:\n  " + "\n  ".join(c.name for c in candidates))
        path = candidates[0]
    payload = json.loads(path.read_text())
    if not isinstance(payload, dict) or "runs" not in payload:
        raise SystemExit(
            f"{path} is not a PV11 result file: expected a dict with a "
            f"'runs' key, got "
            f"{type(payload).__name__} with keys "
            f"{sorted(payload)[:6] if isinstance(payload, dict) else 'n/a'}. "
            f"Refusing to guess -- a fallback here is how PV10's gate read "
            f"n=1 and reported a spurious FAIL.")
    runs = payload["runs"]
    if not isinstance(runs, list) or not runs:
        raise SystemExit(f"{path}: 'runs' is empty or not a list")
    for r in runs:
        for field in ("state_uid", "block", "cell", "first_action", "alpha"):
            if field not in r:
                raise SystemExit(
                    f"{path}: an episode lacks '{field}' -- the driver and "
                    f"this evaluator disagree on the record schema")
    return runs, payload


def check_completeness(runs: list[dict]) -> list[str]:
    """Missing / duplicate / extra states are ERRORS, never a silent subset."""
    errors = []
    uids = [r["state_uid"] for r in runs]
    dupes = {u for u in uids if uids.count(u) > 1}
    if dupes:
        errors.append(f"duplicate state_uids: {sorted(dupes)}")

    bank_path = HERE / "pv11_state_bank.json"
    if bank_path.exists():
        bank = json.loads(bank_path.read_text())
        expected = {s["state_uid"] for s in bank["states"]}
        got = set(uids)
        missing = expected - got
        extra = got - expected
        if extra:
            errors.append(f"{len(extra)} states not in the bank: "
                          f"{sorted(extra)[:5]}")
        # A block-restricted run is legitimate; a partial BLOCK is not.
        for block in ("commitment", "acquisition"):
            b_expected = {s["state_uid"] for s in bank["states"]
                          if s["block"] == block}
            b_got = got & b_expected
            if b_got and b_got != b_expected:
                errors.append(
                    f"{block}: {len(b_expected - b_got)} states missing "
                    f"(have {len(b_got)}/{len(b_expected)}) -- a partial "
                    f"block cannot be gated")
    alphas = {r["alpha"] for r in runs}
    if alphas != {0.0}:
        errors.append(f"gate is defined on alpha=0 only; found {alphas}")
    versions = {r.get("policy_parser_version") for r in runs}
    if len(versions) > 1:
        errors.append(f"mixed parser versions: {versions}")
    banks = {r.get("state_bank_version") for r in runs}
    if len(banks) > 1:
        errors.append(f"mixed state-bank versions: {banks}")
    return errors


# ─────────────────────────────── statistics ─────────────────────────────────

def cell_rows(runs, block, cell):
    return [r for r in runs if r["block"] == block and r["cell"] == cell]


def itt_rate(rows, predicate) -> tuple[float, int, int]:
    """(rate, numerator, denominator). Denominator = ALL rows, invalid too."""
    if not rows:
        return float("nan"), 0, 0
    num = sum(1 for r in rows if predicate(r["first_action"]))
    return num / len(rows), num, len(rows)


def valid_only_rate(rows, predicate) -> tuple[float, int, int]:
    valid = [r for r in rows if r["first_action"]["valid"]]
    if not valid:
        return float("nan"), 0, 0
    num = sum(1 for r in valid if predicate(r["first_action"]))
    return num / len(valid), num, len(valid)


def _is_commit(fa) -> bool:
    return fa["kind"] == "commit"


def _is_probe_sample(fa) -> bool:
    return fa["kind"] == "sample" and bool(fa.get("is_probe"))


def evaluate(runs: list[dict]) -> dict:
    """Compute M1, M2 and the interface check. No side effects."""
    out = {"errors": check_completeness(runs)}

    # ── interface validity (NOT a capability criterion) ────────────────────
    n_valid = sum(1 for r in runs if r["first_action"]["valid"])
    out["interface"] = {
        "parseable_first_action": n_valid / len(runs),
        "n_valid": n_valid,
        "n_total": len(runs),
        "threshold": INTERFACE_THRESHOLD,
        "passes": _at_least(n_valid / len(runs),
                            INTERFACE_THRESHOLD),
        "note": "interface check, NOT a capability criterion",
    }

    # ── M1: commitment responds to evidence strength ───────────────────────
    comm = [r for r in runs if r["block"] == "commitment"]
    m1 = {"cells": {}, "applicable": bool(comm)}
    if comm:
        for cell in COMMITMENT_CELLS:
            rows = cell_rows(runs, "commitment", cell)
            rate, num, den = itt_rate(rows, _is_commit)
            vrate, vnum, vden = valid_only_rate(rows, _is_commit)
            m1["cells"][cell] = {
                "itt": rate, "itt_num": num, "itt_den": den,
                "valid_only": vrate, "valid_num": vnum, "valid_den": vden,
            }
        strong = [r for r in comm if r["cell"].startswith("strong/")]
        weak = [r for r in comm if r["cell"].startswith("weak/")]
        s_rate, s_num, s_den = itt_rate(strong, _is_commit)
        w_rate, w_num, w_den = itt_rate(weak, _is_commit)
        m1.update({
            "strong_itt": s_rate, "strong_num": s_num, "strong_den": s_den,
            "weak_itt": w_rate, "weak_num": w_num, "weak_den": w_den,
            "difference": s_rate - w_rate,
            "threshold": M1_THRESHOLD,
            "passes": _at_least(s_rate - w_rate, M1_THRESHOLD),
        })
        # per-horizon, PRINTED and human-read, deliberately NOT mechanized
        m1["by_horizon"] = {}
        for hz in ("short", "long"):
            s = itt_rate([r for r in comm if r["cell"] == f"strong/{hz}"],
                         _is_commit)[0]
            w = itt_rate([r for r in comm if r["cell"] == f"weak/{hz}"],
                         _is_commit)[0]
            m1["by_horizon"][hz] = {"strong": s, "weak": w, "difference": s - w}
    out["M1"] = m1

    # ── M2: probe sampling responds to sample size at a fixed rate ─────────
    acq = [r for r in runs if r["block"] == "acquisition"]
    m2 = {"cells": {}, "applicable": bool(acq)}
    if acq:
        for cell in ACQUISITION_CELLS:
            rows = cell_rows(runs, "acquisition", cell)
            rate, num, den = itt_rate(rows, _is_probe_sample)
            vrate, vnum, vden = valid_only_rate(rows, _is_probe_sample)
            # within-cell reference: PER-CELL DIAGNOSTIC, not cross-cell
            # comparable and not part of PASS/FAIL. In low_n the probe is the
            # only low-sample arm ("is the under-sampled arm preferred"); in
            # matched_n every arm sits at 20 ("is the low-rate arm preferred
            # at equal n"). Different questions, same formula.
            others = []
            for r in rows:
                fa = r["first_action"]
                if fa["kind"] != "sample" or not fa.get("arm"):
                    continue
                if fa.get("is_displayed_best") or fa.get("is_probe"):
                    continue
                others.append(r)
            m2["cells"][cell] = {
                "itt": rate, "itt_num": num, "itt_den": den,
                "valid_only": vrate, "valid_num": vnum, "valid_den": vden,
                "other_nonleader_sample_rate": len(others) / len(rows)
                if rows else float("nan"),
            }
        lo = cell_rows(runs, "acquisition", "low_n/low_rate")
        mt = cell_rows(runs, "acquisition", "matched_n/low_rate")
        lo_rate, lo_num, lo_den = itt_rate(lo, _is_probe_sample)
        mt_rate, mt_num, mt_den = itt_rate(mt, _is_probe_sample)
        m2.update({
            "low_n_itt": lo_rate, "low_n_num": lo_num, "low_n_den": lo_den,
            "matched_n_itt": mt_rate, "matched_n_num": mt_num,
            "matched_n_den": mt_den,
            "difference": lo_rate - mt_rate,
            "threshold": M2_THRESHOLD,
            "passes": _at_least(lo_rate - mt_rate, M2_THRESHOLD),
        })
        # rate-chasing contrast: descriptive only, never gated
        hi = itt_rate(cell_rows(runs, "acquisition", "low_n/high_rate"),
                      _is_probe_sample)[0]
        m2["rate_contrast_descriptive"] = {
            "low_n_high_rate": hi, "low_n_low_rate": lo_rate,
            "note": ("descriptive. A probe sampled mainly under high_rate "
                     "reads as rate-chasing, not information-seeking."),
        }
    out["M2"] = m2

    applicable = [m for m in (m1, m2) if m["applicable"]]
    out["verdict"] = ("PASS" if (not out["errors"] and applicable
                                 and all(m["passes"] for m in applicable))
                      else "FAIL")
    return out


# ─────────────────────────────── reporting ──────────────────────────────────

def _pct(x) -> str:
    return "  n/a" if x != x else f"{x:5.3f}"


def report(res: dict) -> None:
    print("=" * 72)
    print("PV11 alpha=0 MANIPULATION GATE")
    print("=" * 72)
    print("Asks whether this controlled interface elicits the prerequisite")
    print("sensitivities. NOT a competence claim. Denominator is ITT:")
    print("invalid counts in the denominator and in no numerator.")
    print()

    if res["errors"]:
        print("ERRORS (the gate cannot be read):")
        for e in res["errors"]:
            print(f"  ! {e}")
        print()

    it = res["interface"]
    print(f"INTERFACE  parseable first action "
          f"{_pct(it['parseable_first_action'])} "
          f"({it['n_valid']}/{it['n_total']})  >= {it['threshold']}  "
          f"{'ok' if it['passes'] else 'LOW'}")
    print(f"           {it['note']}")
    print()

    m1 = res["M1"]
    if m1["applicable"]:
        print("M1  first-step COMMIT vs evidence strength")
        for cell in COMMITMENT_CELLS:
            c = m1["cells"][cell]
            print(f"      {cell:14s} ITT {_pct(c['itt'])} "
                  f"({c['itt_num']}/{c['itt_den']})   "
                  f"valid-only {_pct(c['valid_only'])} "
                  f"({c['valid_num']}/{c['valid_den']})")
        print(f"      strong {_pct(m1['strong_itt'])} "
              f"({m1['strong_num']}/{m1['strong_den']})  -  "
              f"weak {_pct(m1['weak_itt'])} "
              f"({m1['weak_num']}/{m1['weak_den']})  =  "
              f"{m1['difference']:+.3f}   >= {m1['threshold']}   "
              f"{'PASS' if m1['passes'] else 'FAIL'}")
        print("      by horizon (descriptive, NOT mechanized):")
        for hz, d in m1["by_horizon"].items():
            print(f"        {hz:6s} strong {_pct(d['strong'])} "
                  f"weak {_pct(d['weak'])}  diff {d['difference']:+.3f}")
        print()

    m2 = res["M2"]
    if m2["applicable"]:
        print("M2  first-step probe SAMPLE vs probe sample size "
              "(displayed rate held at .40)")
        for cell in ACQUISITION_CELLS:
            c = m2["cells"][cell]
            print(f"      {cell:20s} ITT {_pct(c['itt'])} "
                  f"({c['itt_num']}/{c['itt_den']})   "
                  f"valid-only {_pct(c['valid_only'])} "
                  f"({c['valid_num']}/{c['valid_den']})")
        print(f"      low_n {_pct(m2['low_n_itt'])} "
              f"({m2['low_n_num']}/{m2['low_n_den']})  -  "
              f"matched_n {_pct(m2['matched_n_itt'])} "
              f"({m2['matched_n_num']}/{m2['matched_n_den']})  =  "
              f"{m2['difference']:+.3f}   >= {m2['threshold']}   "
              f"{'PASS' if m2['passes'] else 'FAIL'}")
        rc = m2["rate_contrast_descriptive"]
        print(f"      descriptive: low_n/high_rate "
              f"{_pct(rc['low_n_high_rate'])} vs low_n/low_rate "
              f"{_pct(rc['low_n_low_rate'])}")
        print(f"      within-cell 'other non-leader' rates are PER-CELL "
              f"DIAGNOSTIC, not cross-cell comparable:")
        for cell in ACQUISITION_CELLS:
            print(f"        {cell:20s} "
                  f"{_pct(m2['cells'][cell]['other_nonleader_sample_rate'])}")
        print()

    print("=" * 72)
    print(f"VERDICT: {res['verdict']}")
    if res["verdict"] != "PASS":
        print()
        print("Manipulation-gate failure does not trigger prompt iteration.")
        print("It means that this controlled interface did not elicit the")
        print("prerequisite behavior needed for an interpretable steering")
        print("test; no steered cells are run.")
    else:
        print()
        print("Both prerequisites hold. The -4/+4 cells may now be")
        print("implemented and run on the SAME bank, tapes and parser.")
    print("=" * 72)


# ─────────────────────────────── selftest ───────────────────────────────────

def _synthetic(commit_strong, commit_weak, probe_low, probe_matched,
               invalid_rate=0.0):
    """Synthetic runs with known rates, for discriminating-power checks."""
    runs = []
    bank = json.loads((HERE / "pv11_state_bank.json").read_text())
    for s in bank["states"]:
        i = s["state_id"]
        if s["block"] == "commitment":
            target = commit_strong if s["evidence"] == "strong" else commit_weak
            kind = "commit" if i < round(target * N_PER_CELL) else "sample"
            arm, probe = s["true_best"], False
        else:
            key = (s["probe_sample_size"], s["probe_rate_level"])
            target = {("low_n", "low_rate"): probe_low,
                      ("matched_n", "low_rate"): probe_matched,
                      ("low_n", "high_rate"): probe_low,
                      ("matched_n", "high_rate"): probe_matched}[key]
            probe = i < round(target * N_PER_CELL)
            kind = "sample"
            arm = s["probe_label"] if probe else s["displayed_best"]
        invalid = i >= N_PER_CELL - round(invalid_rate * N_PER_CELL)
        runs.append({
            "state_uid": s["state_uid"], "block": s["block"],
            "cell": s["cell"], "alpha": 0.0,
            "policy_parser_version": "pv10-strict-v2",
            "state_bank_version": "pv11-states-v1",
            "first_action": {
                "kind": "invalid" if invalid else kind,
                "valid": not invalid,
                "action": None if invalid else kind.upper(),
                "arm": None if invalid else arm,
                "invalid_kind": "no_policy" if invalid else None,
                "is_probe": (not invalid) and probe,
                "is_displayed_best": (not invalid) and arm ==
                s.get("displayed_best"),
                "is_true_best": (not invalid) and arm == s.get("true_best"),
            },
        })
    return runs


def selftest() -> int:
    fails = []

    r = evaluate(_synthetic(0.80, 0.30, 0.60, 0.20))
    if r["verdict"] != "PASS":
        fails.append(f"a clearly-sensitive model did not PASS: {r['verdict']}")

    r = evaluate(_synthetic(0.50, 0.50, 0.60, 0.20))
    if r["M1"]["passes"] or r["verdict"] == "PASS":
        fails.append("M1 passed with zero evidence sensitivity")

    r = evaluate(_synthetic(0.80, 0.30, 0.25, 0.25))
    if r["M2"]["passes"] or r["verdict"] == "PASS":
        fails.append("M2 passed under uniform-random probe sampling")

    # exactly at threshold must PASS (frozen: >=, ties are not re-adjudicated)
    r = evaluate(_synthetic(0.45, 0.30, 0.35, 0.20))
    if not (r["M1"]["passes"] and r["M2"]["passes"]):
        fails.append("a difference of exactly 0.15 did not pass a >= rule")

    # just below threshold must FAIL
    r = evaluate(_synthetic(0.40, 0.30, 0.30, 0.20))
    if r["M1"]["passes"] or r["M2"]["passes"]:
        fails.append("a difference of 0.10 passed a 0.15 threshold")

    # invalid must dilute ITT but not valid-only
    r = evaluate(_synthetic(0.80, 0.30, 0.60, 0.20, invalid_rate=0.25))
    c = r["M1"]["cells"]["strong/short"]
    if not (c["itt"] < c["valid_only"]):
        fails.append("invalid episodes did not dilute the ITT rate")
    if r["interface"]["passes"]:
        fails.append("a 25% invalid rate passed the interface check")

    # a partial block must ERROR rather than gate on a subset
    runs = _synthetic(0.80, 0.30, 0.60, 0.20)
    r = evaluate(runs[:-5])
    if not r["errors"]:
        fails.append("a partial block did not raise a completeness error")
    if r["verdict"] == "PASS":
        fails.append("a partial block still reported PASS")

    # duplicates must ERROR
    r = evaluate(runs + runs[:1])
    if not any("duplicate" in e for e in r["errors"]):
        fails.append("a duplicated state was not flagged")

    # non-zero alpha must ERROR
    steered = [dict(x, alpha=4.0) for x in runs]
    r = evaluate(steered)
    if not any("alpha=0" in e for e in r["errors"]):
        fails.append("a steered cell was accepted by the gate")

    if fails:
        print(f"SELFTEST FAIL ({len(fails)})")
        for f in fails:
            print(f"  - {f}")
        return 1
    print("ok  analyze_bandit_pv11_gate.py --selftest  (9 checks)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--result", help="PV11 result JSON or its directory")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--json", action="store_true", help="emit raw JSON")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if not args.result:
        ap.error("--result or --selftest is required")

    runs, _ = load_runs(Path(args.result))
    res = evaluate(runs)
    if args.json:
        print(json.dumps(res, indent=2, sort_keys=True))
    else:
        report(res)
    return 0 if res["verdict"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
