#!/usr/bin/env python3.10
"""Competence gate evaluator (BanditExperiment_LiteratureReview.md §3.6).

FROZEN BEFORE THE DATA EXISTS. The four rules are pre-registered in the design
doc, but "pre-registered" is not the same as "implemented" — the rules leave
implementation freedom (window boundaries, strict vs non-strict comparison,
what to do with a missing seed) and each of those choices can flip a verdict.
So they are resolved HERE, in advance, and tested against synthetic fixtures
plus the frozen manifest. Do not edit this file after A0_BARE has been run.

THE FOUR RULES (all four must hold for a condition to pass):

  1. discovery beats Greedy lock-in
        SuffFailFreq_model(T/2) < SuffFailFreq_Greedy(T/2)
     ... and the difference is not produced by non-novel churn (reported as a
     diagnostic; see NON-NOVEL CHURN below for why it cannot be mechanical).
  2. not uniform flailing
        KxMinFrac_model(T) < KxMinFrac_Random(T)
        AND KxMinFrac_model(T) < KxMinFrac_model(T/2)
  3. can exploit once a good arm is found
        post-discovery late empirical-best adherence > 1/K
  4. minimal behavioural benefit
        late OptFrac > 1/K

RESOLVED DEGREES OF FREEDOM (each one could change a verdict):

  * T/2 boundary. `half = T // 2`, and every "(T/2)" quantity is evaluated on
    the SUFFIX/PREFIX split at that index: SuffFail(T/2) asks whether the best
    arm appears in rounds [half, T) (a SUFFIX, per Krishnamurthy); KxMinFrac
    (T/2) is computed on the PREFIX [0, half) — it is the "earlier in the run"
    term of rule 2's decreasing-over-time comparison, so it must be a prefix,
    not a suffix. This asymmetry is deliberate and is the single easiest thing
    to get silently wrong.
  * "decreasing over time" compares exactly two points: the full-horizon value
    KxMinFrac(T) against the first-half value KxMinFrac(T/2). No trend fit, no
    per-quartile test.
  * strict `<` everywhere, and strict `>` in rules 3 and 4. A tie fails. With
    continuous statistics exact ties are near-impossible except in degenerate
    cases (e.g. a model that never explores), and in those cases failing is
    the correct reading.
  * 1/K uses the environment's K, so Easy = 0.25 and Hard = 0.20.
  * "late" = the same suffix window [half, T), matching late_opt_frac in
    bandit_reference._package. Rules 3 and 4 therefore share one window.
  * SEEDS. The evaluated seed set must be EXACTLY the frozen bank. A missing,
    duplicated, or extra seed is a hard ERROR, never a silent subset — the
    comparison is paired against baselines run on that bank, and quietly
    intersecting would change the comparison basis. See check_seed_integrity.
  * Baselines are recomputed from bandit_reference on the same bank and the
    same reward tapes. They are cross-checked against the frozen manifest and
    a mismatch is an ERROR: it means the environment or bank drifted, so the
    pre-registration no longer describes what is being run.

NON-NOVEL CHURN (rule 1's second clause) is NOT mechanized. Distinguishing
"explored a new arm" from "churned among already-tried arms" is a mechanism
question that the doc asks to be read alongside discovery metrics, and a
threshold invented here would be exactly the post-hoc freedom this file exists
to prevent. So novel-arm discovery and non-novel churn are COMPUTED and
REPORTED, rule 1's mechanical part is the inequality alone, and the verdict is
flagged for human review when churn is high while discovery is low.

PAIRED BOOTSTRAP. Point estimates decide the gate (mechanical, per the doc);
the paired per-seed bootstrap is reported alongside as uncertainty and never
overrides. Input pairing is by seed via bandit_reference.paired_bootstrap_ci,
which errors on duplicate or mismatched seed sets.

Usage:
    python3.10 evaluate_competence_gate.py --selftest
    python3.10 evaluate_competence_gate.py \
        --result /data1/paveen/Dopamine/components/llama3/pv6_easy_bare
    python3.10 evaluate_competence_gate.py --result DIR1 --result DIR2
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

import bandit_reference as br

MANIFEST = "bandit_pv6_baseline_manifest.json"


# ─────────────────────────── per-run quantities ─────────────────────────────

def novelty_split(choices: list[str]) -> dict:
    """Split switches into NOVEL (first-ever pull of an arm) and NON-NOVEL
    (a switch to an already-tried arm) — rule 1's churn diagnostic.

    Reported, not thresholded: see the module docstring.
    """
    seen: set[str] = set()
    novel = churn = switches = 0
    prev = None
    for c in choices:
        if c not in seen:
            novel += 1
            seen.add(c)
        elif prev is not None and c != prev:
            churn += 1
        if prev is not None and c != prev:
            switches += 1
        prev = c
    n = len(choices)
    return {
        "n_arms_discovered": len(seen),
        "novel_pulls": novel,
        "non_novel_churn": churn,
        "switch_rate": switches / (n - 1) if n > 1 else float("nan"),
        "churn_rate": churn / (n - 1) if n > 1 else float("nan"),
    }


def post_discovery_adherence(run: dict, half: int) -> float:
    """Rule 3: in the late window, how often does the policy pick an arm with
    the highest empirical mean AT THAT MOMENT?

    "post-discovery" = restricted to the late window [half, T), and only over
    rounds where at least one arm has been tried (always true after round 0).
    Ties all count as adherence: several arms can legitimately share the top
    observed mean, and calling a tied pick non-adherent would understate
    exploitation. NaN when the window is empty.
    """
    choices, fb = run["choices"], run["feedbacks"]
    n: dict[str, int] = {}
    s: dict[str, float] = {}
    hit = tot = 0
    for t, (c, r) in enumerate(zip(choices, fb)):
        if t >= half and n:
            means = {a: s[a] / n[a] for a in n}
            top = max(means.values())
            tot += 1
            if c in means and means[c] >= top - 1e-9:
                hit += 1
        n[c] = n.get(c, 0) + 1
        s[c] = s.get(c, 0.0) + r
    return hit / tot if tot else float("nan")


def _mean(xs):
    xs = [x for x in xs if x == x]
    return sum(xs) / len(xs) if xs else float("nan")


# ─────────────────────────────── integrity ──────────────────────────────────

def check_seed_integrity(runs: list[dict], bank: list[int]) -> list[str]:
    """A missing/duplicate/extra seed is an ERROR, not a silent subset."""
    seeds = [r["seed"] for r in runs]
    errs = []
    if len(set(seeds)) != len(seeds):
        dupes = sorted({s for s in seeds if seeds.count(s) > 1})
        errs.append(f"duplicate seeds in results: {dupes}")
    missing = sorted(set(bank) - set(seeds))
    extra = sorted(set(seeds) - set(bank))
    if missing:
        errs.append(f"missing seeds (frozen bank not fully run): {missing}")
    if extra:
        errs.append(f"seeds not in the frozen bank: {extra}")
    return errs


def check_baseline_drift(env, bank, baselines) -> list[str]:
    """Recomputed baselines must match the frozen manifest.

    A mismatch means the environment, bank, tape or a policy definition
    changed since the manifest was frozen — in which case the pre-registration
    no longer describes what is being run, and the gate must not be evaluated.
    """
    if not os.path.exists(MANIFEST):
        return [f"{MANIFEST} not found — the gate basis is not frozen"]
    man = json.load(open(MANIFEST))
    key = next((k for k, v in man["environments"].items()
                if v["name"] == env.name), None)
    if key is None:
        return [f"{env.name} not in the frozen manifest"]
    m = man["environments"][key]
    errs = []
    if m["seed_bank"] != list(bank):
        errs.append("seed bank differs from the frozen manifest")
    half = env.horizon // 2
    for pol in ("greedy", "random"):
        got_sff = br.suff_fail_freq(baselines[pol], half)
        want_sff = m["policies"][pol]["suff_fail_freq_half"]["point"]
        got_kmf = br.mean_k_min_frac(baselines[pol])
        want_kmf = m["policies"][pol]["k_min_frac_full"]["point"]
        if abs(got_sff - want_sff) > 1e-9:
            errs.append(f"{pol} SuffFailFreq drift: {got_sff} vs manifest {want_sff}")
        if abs(got_kmf - want_kmf) > 1e-9:
            errs.append(f"{pol} KxMinFrac drift: {got_kmf} vs manifest {want_kmf}")
    return errs


# ──────────────────────────────── the gate ──────────────────────────────────

def evaluate(runs: list[dict], env: br.Environment, bank: list[int],
             label: str = "") -> dict:
    half = env.horizon // 2
    inv_k = 1.0 / env.k

    errors = check_seed_integrity(runs, bank)
    # The stored trajectory must match the environment spec being evaluated
    # against. If it does not, every window index (half, late, suffix) is
    # computed against the wrong horizon and each rule reads a different
    # trajectory than it names — so this is an ERROR, not a warning.
    bad_len = {len(r["choices"]) for r in runs} - {env.horizon}
    if bad_len:
        errors.append(
            f"trajectory length {sorted(bad_len)} != environment horizon "
            f"{env.horizon}; window indices would not match the data")
    baselines = {
        "greedy": [br.run_greedy(s, env, br.RewardTape(s, env)) for s in bank],
        "random": [br.run_random(s, env, br.RewardTape(s, env)) for s in bank],
    }
    errors += check_baseline_drift(env, bank, baselines)

    # rule 1
    m_sff = br.suff_fail_freq(runs, half)
    g_sff = br.suff_fail_freq(baselines["greedy"], half)
    r1 = m_sff < g_sff

    # rule 2 — note the asymmetry: KxMinFrac(T/2) is a PREFIX
    m_kmf = br.mean_k_min_frac(runs)
    m_kmf_half = br.mean_k_min_frac(runs, half)
    rnd_kmf = br.mean_k_min_frac(baselines["random"])
    r2a = m_kmf < rnd_kmf
    r2b = m_kmf < m_kmf_half
    r2 = r2a and r2b

    # rules 3 and 4 share the late window [half, T)
    adher_vals = [post_discovery_adherence(r, half) for r in runs]
    adher = _mean(adher_vals)
    # NaN fails closed (nan > x is False), which is the right verdict — but
    # "undefined" and "too low" are different situations, so an all-NaN
    # adherence is surfaced as an explicit error rather than reading as a
    # quiet rule-3 failure.
    n_defined = sum(1 for v in adher_vals if v == v)
    if n_defined == 0:
        errors.append("rule 3 adherence undefined for every run "
                      "(empty late window?) — not the same as 'too low'")
    r3 = adher > inv_k
    late = _mean([r["late_opt_frac"] for r in runs])
    r4 = late > inv_k

    churn = [novelty_split(r["choices"]) for r in runs]
    churn_mean = {k: _mean([c[k] for c in churn]) for k in churn[0]} if churn else {}

    # paired uncertainty (reported, never decisive)
    boot = {}
    try:
        boot["suff_fail_vs_greedy"] = br.paired_bootstrap_ci(
            runs, baselines["greedy"],
            lambda r: float(br.suffix_failure(r["choices"], r["best_arm"], half)))
        boot["k_min_frac_vs_random"] = br.paired_bootstrap_ci(
            runs, baselines["random"],
            lambda r: br.k_min_frac(r["choices"], list(r["arm_map"])))
    except ValueError as e:
        boot["error"] = str(e)

    passed = bool(r1 and r2 and r3 and r4) and not errors
    # rule 1's churn clause is advisory: flag, never auto-fail.
    review = bool(r1 and churn_mean.get("churn_rate", 0) > 0.5
                  and churn_mean.get("n_arms_discovered", env.k) < env.k)

    return {
        "label": label, "environment": env.name, "k": env.k,
        "horizon": env.horizon, "n_runs": len(runs), "errors": errors,
        "rules": {
            "1_discovery_beats_greedy": {
                "pass": bool(r1), "model": m_sff, "greedy": g_sff,
                "test": "SuffFailFreq_model(T/2) < SuffFailFreq_Greedy(T/2)"},
            "2_not_uniform_flailing": {
                "pass": bool(r2), "vs_random": bool(r2a), "decreasing": bool(r2b),
                "model_T": m_kmf, "random_T": rnd_kmf, "model_half": m_kmf_half,
                "test": "KxMinFrac(T) < Random(T) AND KxMinFrac(T) < KxMinFrac(T/2)"},
            "3_post_discovery_adherence": {
                "pass": bool(r3), "value": adher, "threshold": inv_k,
                "test": "late empirical-best adherence > 1/K"},
            "4_late_opt_frac": {
                "pass": bool(r4), "value": late, "threshold": inv_k,
                "test": "late OptFrac > 1/K"},
        },
        "churn_diagnostic": churn_mean,
        "needs_human_review": review,
        "paired_bootstrap": boot,
        "PASSED": passed,
    }


def report(res: dict) -> None:
    print("=" * 76)
    print(f"COMPETENCE GATE  {res['label']}")
    print(f"  env={res['environment']} K={res['k']} T={res['horizon']} "
          f"n_runs={res['n_runs']}")
    print("=" * 76)
    if res["errors"]:
        print("ERRORS (gate not evaluable):")
        for e in res["errors"]:
            print("  -", e)
        print()
    for name, r in res["rules"].items():
        mark = "PASS" if r["pass"] else "FAIL"
        print(f"  [{mark}] rule {name}")
        print(f"         {r['test']}")
        if "model" in r:
            print(f"         model {r['model']:.4f}  vs  greedy {r['greedy']:.4f}")
        elif "model_T" in r:
            print(f"         model(T) {r['model_T']:.4f}  random(T) {r['random_T']:.4f}"
                  f"  model(T/2) {r['model_half']:.4f}")
            print(f"         vs_random={r['vs_random']}  decreasing={r['decreasing']}")
        else:
            print(f"         value {r['value']:.4f}  threshold {r['threshold']:.4f}")
    c = res["churn_diagnostic"]
    if c:
        print(f"\n  churn diagnostic (rule 1 clause 2, REPORTED not thresholded):")
        print(f"    arms discovered {c['n_arms_discovered']:.2f}/{res['k']}  "
              f"churn_rate {c['churn_rate']:.3f}  switch_rate {c['switch_rate']:.3f}")
    b = res["paired_bootstrap"]
    if "error" in b:
        print(f"\n  paired bootstrap unavailable: {b['error']}")
    else:
        print("\n  paired bootstrap (uncertainty only — the gate is the point estimate):")
        for k, v in b.items():
            print(f"    {k:24s} {v['point']:+.4f}  [{v['lo']:+.4f}, {v['hi']:+.4f}]")
    if res["needs_human_review"]:
        print("\n  ** FLAG: rule 1 passes but churn is high with incomplete "
              "discovery.\n     Read the mechanism before calling this discovery.")
    print(f"\n  VERDICT: {'PASS' if res['PASSED'] else 'FAIL'}")


def load_result_dir(path: str):
    files = sorted(glob.glob(os.path.join(path, "mdf_*", "bandit_pv6_*.json")))
    if not files:
        raise SystemExit(f"no pv6 result JSON under {path}")
    out = []
    for f in files:
        d = json.load(open(f))
        if float(d["alpha"]) != 0.0:
            continue                       # the gate is an alpha=0 statement
        env = br.get_environment(
            {"reference_easy": "easy", "reference_hard": "hard",
             "native_floor": "native_floor"}[d["environment"]["name"]])
        out.append((d, env, f))
    if not out:
        raise SystemExit(f"no alpha=0 cell under {path}")
    return out


# ──────────────────────────────── selftest ──────────────────────────────────

def selftest() -> int:
    """Synthetic fixtures: policies with KNOWN behaviour must land on the
    intended side of every rule. Run before the real data exists."""
    fails = []

    def check(cond, label):
        print(f"  {'PASS' if cond else 'FAIL'}  {label}")
        if not cond:
            fails.append(label)

    env = br.get_environment("easy")
    bank = br.build_seed_bank(env)
    half = env.horizon // 2

    print("[1] oracle-like policy passes all four rules")
    oracle = [br.run_oracle(s, env, br.RewardTape(s, env)) for s in bank]
    r = evaluate(oracle, env, bank, "oracle")
    check(r["rules"]["1_discovery_beats_greedy"]["pass"], "oracle: rule 1")
    check(r["rules"]["3_post_discovery_adherence"]["pass"], "oracle: rule 3")
    check(r["rules"]["4_late_opt_frac"]["pass"], "oracle: rule 4")
    # oracle plays ONE arm, so KxMinFrac = 0 at both windows -> rule 2's
    # "decreasing" clause is 0 < 0 = False. Oracle is a reward ceiling, not a
    # competent explorer; failing rule 2 is CORRECT, and is why the doc keeps
    # oracle out of the comparable-policy set.
    check(not r["rules"]["2_not_uniform_flailing"]["decreasing"],
          "oracle: rule 2 decreasing is False (single-arm, correctly not competent)")

    print("\n[2] random policy fails rule 2 (uniform flailing)")
    rand = [br.run_random(s, env, br.RewardTape(s, env)) for s in bank]
    r = evaluate(rand, env, bank, "random")
    check(not r["rules"]["2_not_uniform_flailing"]["vs_random"],
          "random: not < random (identical policy)")
    check(not r["PASSED"], "random: overall FAIL")

    print("\n[3] greedy fails rule 1 against itself")
    greedy = [br.run_greedy(s, env, br.RewardTape(s, env)) for s in bank]
    r = evaluate(greedy, env, bank, "greedy")
    check(not r["rules"]["1_discovery_beats_greedy"]["pass"],
          "greedy: rule 1 fails (not strictly < itself)")
    check(not r["PASSED"], "greedy: overall FAIL")

    print("\n[4] Thompson-like policy is the intended PASS case")
    import run_bandit_algorithmic_baseline as algo
    ts = [algo._pv6_thompson(s, env, br.RewardTape(s, env)) for s in bank]
    r = evaluate(ts, env, bank, "thompson")
    for name, rr in r["rules"].items():
        check(rr["pass"], f"thompson: rule {name}")
    check(r["PASSED"], "thompson: overall PASS")

    print("\n[5] window semantics")
    check(half == env.horizon // 2, "half == T // 2")
    # SuffFail is a SUFFIX; KxMinFrac(T/2) is a PREFIX. A policy that plays
    # uniformly early then locks on one arm must show KxMinFrac decreasing.
    names = list(br.RewardTape(bank[0], env).arm_map)
    mixed = names * (half // env.k) + [names[0]] * (env.horizon - half)
    kf_full = br.k_min_frac(mixed, names)
    kf_half = br.k_min_frac(mixed, names, half)
    check(kf_full < kf_half,
          "explore-then-commit: KxMinFrac(T) < KxMinFrac(T/2) (prefix semantics)")
    check(br.suffix_failure(mixed, names[1], half),
          "suffix_failure reads the SUFFIX [half, T)")

    print("\n[6] strictness and thresholds")
    check(not (0.25 < 0.25), "strict < : a tie fails rule 1")
    check(abs(1.0 / env.k - 0.25) < 1e-12, "1/K = 0.25 for Easy K=4")
    check(abs(1.0 / br.get_environment("hard").k - 0.20) < 1e-12,
          "1/K = 0.20 for Hard K=5")

    print("\n[7] seed integrity is an ERROR, never a silent subset")
    check(check_seed_integrity(ts[:-1], bank), "missing seed -> error")
    check(check_seed_integrity(ts + [ts[0]], bank), "duplicate seed -> error")
    check(not check_seed_integrity(ts, bank), "exact bank -> no error")
    r_missing = evaluate(ts[:-1], env, bank, "missing")
    check(not r_missing["PASSED"], "a seed-integrity error forces FAIL")

    print("\n[8] baseline drift against the frozen manifest")
    base = {"greedy": greedy, "random": rand}
    check(not check_baseline_drift(env, bank, base), "no drift on the frozen bank")
    check(check_baseline_drift(env, list(bank[:-1]) + [999], base),
          "a changed bank is reported as drift")

    print("\n[8b] a horizon mismatch is an ERROR, not a silent rewindowing")
    short = [dict(r, choices=r["choices"][:20], feedbacks=r["feedbacks"][:20])
             for r in ts]
    r_short = evaluate(short, env, bank, "short")
    check(any("horizon" in e for e in r_short["errors"]),
          "truncated trajectories are reported against the env horizon")
    check(not r_short["PASSED"], "a horizon mismatch forces FAIL")

    print("\n[9] hard environment evaluates too")
    henv = br.get_environment("hard")
    hbank = br.build_seed_bank(henv)
    hts = [algo._pv6_thompson(s, henv, br.RewardTape(s, henv)) for s in hbank]
    rh = evaluate(hts, henv, hbank, "thompson-hard")
    check(rh["k"] == 5 and abs(rh["rules"]["4_late_opt_frac"]["threshold"] - 0.2) < 1e-12,
          "hard: threshold is 1/5")
    check(not rh["errors"], "hard: no integrity or drift errors")

    print("\n" + "=" * 60)
    if fails:
        print(f"SELFTEST FAILED ({len(fails)}):")
        for f in fails:
            print("  -", f)
        return 1
    print("SELFTEST PASSED")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--result", action="append", default=[],
                    help="pv6 result dir (repeatable), e.g. .../pv6_easy_bare")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--json", default=None, help="write verdicts to this path")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if not args.result:
        ap.error("give --result DIR (repeatable) or --selftest")

    out = []
    for path in args.result:
        for d, env, f in load_result_dir(path):
            label = os.path.basename(path.rstrip("/"))
            if "bare" not in label:
                print(f"\n### NOTE: {label} is not a reference-bare condition.")
                print("### The competence gate is defined ONLY on reference-bare")
                print("### K=4/K=5. Reported for completeness; it does not select")
                print("### a competence anchor.\n")
            res = evaluate(d["runs"], env, d["bank_report"]["seeds"], label)
            report(res)
            out.append(res)

    if args.json:
        with open(args.json, "w") as fw:
            json.dump(out, fw, indent=2)
        print(f"\nwrote {args.json}")
    return 0 if all(r["PASSED"] for r in out) else 1


if __name__ == "__main__":
    sys.exit(main())
